x-defaults:
  &svc
  hostname: ${CONTAINER_HOSTNAME}
  tty: true

x-build-args: &args
  args:
    - UBUNTU_VERSION=${CONTAINER_UBUNTU_VERSION}
    - USERNAME=${CONTAINER_USERNAME}
    - PASSWORD=${CONTAINER_PASSWORD}
    - UID=${CONTAINER_UID}
    - TIMEZONE=${CONTAINER_TIMEZONE}
    - USER_PRIVILEGE_LEVEL=standard
    - CONDA_DIR=${MINICONDA_DIR}
    - CONDA_VERSION=${MINICONDA_VERSION}
    - CONDA_OS=${MINICONDA_OS}
    - CONDA_ARCH=${MINICONDA_ARCH}
    - WINE_GITHUB=${WINE_GITHUB}
    - WINE_COMMIT=${WINE_COMMIT}
    - SLURM_VER=${SLURM_VER}

services:
  mesospim_utils:
    image: cbipitt/mesospim_utils:test
    network_mode: "host"
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
              count: all # or specify a number, e.g., 1
    command: [
      "/bin/bash", "-lc",
      "sudo /etc/startup.sh; exec /bin/bash -l"
    ]
#    user: $(id -u):$(id -g)

    volumes:
      - config_dir:/opt/mesospim_utils/mesospim_utils/config #Location to store mesospim_utils config
      - c:/test_data:/test_data
      #- h20:/h20
      #- faststore:/CBI_FastStore
  build-mesospim-utils:
    <<: *svc
    build:
      context: .
      <<: *args
    image: ${DOCKER_HUB_REPO}:${TAG}
    container_name: mesospim-utils

volumes:
  config_dir:
    driver: local
    driver_opts:
      type: cifs
      device: "//faststore.cbi.pitt.edu/CBI_FastStore/cbiPythonTools/mesospim_utils/docker/config"
      o: "vers=3.0,guest,noperm,file_mode=0777,dir_mode=0777"
#  h20:
#    driver: local
#    driver_opts:
#      type: cifs
#      device: "//tn.cbi.pitt.edu/h20"
#      o: "vers=3.0,guest,noperm,file_mode=0777,dir_mode=0777"
#  faststore:
#    driver: local
#    driver_opts:
#      type: cifs
#      device: "//faststore.cbi.pitt.edu/CBI_FastStore"
#      o: "vers=3.0,guest,noperm,file_mode=0777,dir_mode=0777"

